### PR TITLE
refactor layout

### PR DESCRIPTION
**Pull request by pmenglund**

### CODE REVIEW

**Comment by pmenglund** [comment]
Current dependencies on/for this PR:
* master
  * **PR #14** <a href="https://app.graphite.dev/github/pr/rockset/rockbench/14" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/rockset/rockbench/14?utm_source=stack-comment).

**Review by kwadhwa18 — APPROVED** [review]
thanks for doing this @pmenglund ! this looks so much better

Also @sbaldwin-rs  - this will cause merge conflicts for you :(

**Comment by sbaldwin-rs** [comment]
> thanks for doing this @pmenglund ! this looks so much better
> 
> Also @sbaldwin-rs - this will cause merge conflicts for you :(

This basically nuked my whole PR 😢

**Comment by kwadhwa18** [comment]
> > thanks for doing this @pmenglund ! this looks so much better
> > Also @sbaldwin-rs - this will cause merge conflicts for you :(
> 
> This basically nuked my whole PR 😢

oof .. sorry :(

**Pull request merged**
